/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: plaggy (https://sketchfab.com/plaggy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cc0-awning-47e5fd8a6b194b48aad20425869d15ba
Title: CC0 - Awning
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Terraza = (props) => {
  const { nodes, materials } = useGLTF('/models/terraza.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Awning_Awning_0.geometry}
        material={materials.Awning}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.025}
      />
    </group>
  )
}

useGLTF.preload('/models/terraza.glb')
export default Terraza
